-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 20:23:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_categoria` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_nom` VARCHAR(45) NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_producto` (
  `prod_id` INT NOT NULL AUTO_INCREMENT,
  `prod_nom` TEXT NULL,
  `cat_id` INT NULL,
  PRIMARY KEY (`prod_id`),
  INDEX `fk_t_producto_t_categoria_idx` (`cat_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_producto_t_categoria`
    FOREIGN KEY (`cat_id`)
    REFERENCES `mydb`.`t_categoria` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_unidadmedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_unidadmedida` (
  `um_id` INT NOT NULL AUTO_INCREMENT,
  `um_nom` VARCHAR(45) NULL,
  `um_abr` VARCHAR(45) NULL,
  PRIMARY KEY (`um_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_persona` (
  `per_id` INT NOT NULL AUTO_INCREMENT,
  `per_nom` TEXT NULL,
  `per_ape` TEXT NULL,
  `per_tel` VARCHAR(45) NULL,
  `per_dir` TEXT NULL,
  PRIMARY KEY (`per_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_usuario` (
  `usu_id` INT NOT NULL AUTO_INCREMENT,
  `usu_email` VARCHAR(45) NULL,
  `usu_hash` TEXT NULL,
  `usu_salt` TEXT NULL,
  `usu_est` VARCHAR(45) NULL,
  `usu_tipo` VARCHAR(45) NULL,
  `per_id` INT NULL,
  PRIMARY KEY (`usu_id`),
  INDEX `fk_t_usuario_t_persona1_idx` (`per_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_usuario_t_persona1`
    FOREIGN KEY (`per_id`)
    REFERENCES `mydb`.`t_persona` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_entidad` (
  `ent_id` INT NOT NULL AUTO_INCREMENT,
  `ent_nom` TEXT NULL,
  `ent_rz` TEXT NULL,
  `ent_ruc` VARCHAR(11) NULL,
  `ent_tipo` VARCHAR(45) NULL,
  `per_id` INT NULL,
  PRIMARY KEY (`ent_id`),
  INDEX `fk_t_entidad_t_persona1_idx` (`per_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_entidad_t_persona1`
    FOREIGN KEY (`per_id`)
    REFERENCES `mydb`.`t_persona` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_cotizacion` (
  `coti_id` INT NOT NULL AUTO_INCREMENT,
  `coti_fech` DATE NULL,
  `coti_nro` VARCHAR(45) NULL,
  `coti_est` VARCHAR(45) NULL,
  `usu_id` INT NULL,
  PRIMARY KEY (`coti_id`),
  INDEX `fk_t_cotizacion_t_usuario1_idx` (`usu_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_cotizacion_t_usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `mydb`.`t_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_cotizaciondetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_cotizaciondetalle` (
  `cdet_id` INT NOT NULL AUTO_INCREMENT,
  `cdet_cant` DECIMAL(10,2) NULL,
  `prod_id` INT NULL,
  `um_id` INT NULL,
  `coti_id` INT NULL,
  PRIMARY KEY (`cdet_id`),
  INDEX `fk_t_cotizaciondetalle_t_producto1_idx` (`prod_id` ASC) VISIBLE,
  INDEX `fk_t_cotizaciondetalle_t_unidadmedida1_idx` (`um_id` ASC) VISIBLE,
  INDEX `fk_t_cotizaciondetalle_t_cotizacion1_idx` (`coti_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_cotizaciondetalle_t_producto1`
    FOREIGN KEY (`prod_id`)
    REFERENCES `mydb`.`t_producto` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_cotizaciondetalle_t_unidadmedida1`
    FOREIGN KEY (`um_id`)
    REFERENCES `mydb`.`t_unidadmedida` (`um_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_cotizaciondetalle_t_cotizacion1`
    FOREIGN KEY (`coti_id`)
    REFERENCES `mydb`.`t_cotizacion` (`coti_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_cotizacionproveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_cotizacionproveedor` (
  `cotiprov_id` INT NOT NULL AUTO_INCREMENT,
  `cotiprov_fech` DATE NULL,
  `cotiprov_est` VARCHAR(45) NULL,
  `coti_id` INT NULL,
  `ent_id` INT NULL,
  PRIMARY KEY (`cotiprov_id`),
  INDEX `fk_t_cotizacionproveedor_t_cotizacion1_idx` (`coti_id` ASC) VISIBLE,
  INDEX `fk_t_cotizacionproveedor_t_entidad1_idx` (`ent_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_cotizacionproveedor_t_cotizacion1`
    FOREIGN KEY (`coti_id`)
    REFERENCES `mydb`.`t_cotizacion` (`coti_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_cotizacionproveedor_t_entidad1`
    FOREIGN KEY (`ent_id`)
    REFERENCES `mydb`.`t_entidad` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_cotizacionproveedordetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_cotizacionproveedordetalle` (
  `cotipdet_id` INT NOT NULL AUTO_INCREMENT,
  `cotiprov_id` INT NULL,
  `cotipdet_prec` DECIMAL(10,2) NULL,
  `cdet_id` INT NULL,
  PRIMARY KEY (`cotipdet_id`),
  INDEX `fk_t_cotizacionproveedordetalle_t_cotizacionproveedor1_idx` (`cotiprov_id` ASC) VISIBLE,
  INDEX `fk_t_cotizacionproveedordetalle_t_cotizaciondetalle1_idx` (`cdet_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_cotizacionproveedordetalle_t_cotizacionproveedor1`
    FOREIGN KEY (`cotiprov_id`)
    REFERENCES `mydb`.`t_cotizacionproveedor` (`cotiprov_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_cotizacionproveedordetalle_t_cotizaciondetalle1`
    FOREIGN KEY (`cdet_id`)
    REFERENCES `mydb`.`t_cotizaciondetalle` (`cdet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
