-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 21:47:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_producto` (
  `pro_id` INT NOT NULL AUTO_INCREMENT,
  `pro_nom` VARCHAR(100) NOT NULL,
  `pro_prec` DECIMAL(10,2) NOT NULL,
  `pro_est` VARCHAR(20) NOT NULL DEFAULT 1,
  `pro_desc` TEXT NOT NULL,
  PRIMARY KEY (`pro_id`),
  UNIQUE INDEX `idproducto_UNIQUE` (`pro_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_persona` (
  `per_id` VARCHAR(10) NOT NULL,
  `per_nombre` VARCHAR(415) NOT NULL,
  `per_apellido` VARCHAR(145) NOT NULL,
  `per_direccion` VARCHAR(45) NOT NULL,
  `per_celular` VARCHAR(45) NOT NULL,
  `per_estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`per_id`),
  UNIQUE INDEX `dni_UNIQUE` (`per_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_usuario` (
  `usu_id` INT NOT NULL AUTO_INCREMENT,
  `usu_email` VARCHAR(45) NULL,
  `usu_salt` TEXT NULL,
  `usu_hash` TEXT NULL,
  `usu_tipo` VARCHAR(45) NULL,
  `per_id` INT NULL,
  PRIMARY KEY (`usu_id`),
  INDEX `fk_t_usuario_T_PERSONA1_idx` (`per_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_usuario_T_PERSONA1`
    FOREIGN KEY (`per_id`)
    REFERENCES `mydb`.`t_persona` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_orden` (
  `orde_id` INT NOT NULL AUTO_INCREMENT,
  `orde_tot` DECIMAL(10,2) NOT NULL,
  `orde_est` VARCHAR(45) NOT NULL COMMENT 'en estado colocar los tipos de estado\n',
  `orde_fech` DATE NOT NULL,
  `usu_id` INT NOT NULL,
  PRIMARY KEY (`orde_id`),
  INDEX `fk_t_orden_t_usuario1_idx` (`usu_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_orden_t_usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `mydb`.`t_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_ordendetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_ordendetalle` (
  `odet_id` INT NOT NULL,
  `odet_cant` DECIMAL(10,2) NOT NULL,
  `odet_prec` DECIMAL(10,2) NOT NULL COMMENT 'este precio es la multiplicacion de cantidad por precio unitario del producto\n',
  `orde_id` INT NOT NULL,
  `pro_id` INT NOT NULL,
  PRIMARY KEY (`odet_id`),
  INDEX `fk_t_ordendetalle_t_producto1_idx` (`pro_id` ASC) VISIBLE,
  INDEX `fk_t_ordendetalle_t_orden1_idx` (`orde_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_ordendetalle_t_producto1`
    FOREIGN KEY (`pro_id`)
    REFERENCES `mydb`.`t_producto` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_ordendetalle_t_orden1`
    FOREIGN KEY (`orde_id`)
    REFERENCES `mydb`.`t_orden` (`orde_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_metodopago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_metodopago` (
  `mpago_id` INT NOT NULL,
  `mpado_nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`mpago_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_compra` (
  `compra_id` INT NOT NULL,
  `compra_dcto` DECIMAL(10,2) NOT NULL,
  `compra_tot` DECIMAL(10,2) NOT NULL,
  `compra_dir` TEXT NOT NULL,
  `compra_tel` VARCHAR(9) NOT NULL,
  `compra_nroope` VARCHAR(45) NOT NULL,
  `mpago_id` INT NOT NULL,
  `orde_id` INT NOT NULL,
  PRIMARY KEY (`compra_id`),
  INDEX `fk_compra_ORDEN1_idx` (`orde_id` ASC) VISIBLE,
  INDEX `fk_t_compra_t_metodopago1_idx` (`mpago_id` ASC) VISIBLE,
  CONSTRAINT `fk_compra_ORDEN1`
    FOREIGN KEY (`orde_id`)
    REFERENCES `mydb`.`t_orden` (`orde_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_compra_t_metodopago1`
    FOREIGN KEY (`mpago_id`)
    REFERENCES `mydb`.`t_metodopago` (`mpago_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_comentario` (
  `comen_id` INT NOT NULL,
  `comen_desc` TEXT NOT NULL,
  `comen_fech` DATE NOT NULL,
  `comen_rating` INT NOT NULL,
  `prod_id` INT NOT NULL,
  `usu_id` INT NOT NULL,
  PRIMARY KEY (`comen_id`),
  INDEX `fk_comentario_PRODUCTO1_idx` (`prod_id` ASC) VISIBLE,
  INDEX `fk_t_comentario_t_usuario1_idx` (`usu_id` ASC) VISIBLE,
  CONSTRAINT `fk_comentario_PRODUCTO1`
    FOREIGN KEY (`prod_id`)
    REFERENCES `mydb`.`t_producto` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_comentario_t_usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `mydb`.`t_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_imagen` (
  `ima_id` INT NOT NULL AUTO_INCREMENT,
  `ima_url` TEXT NOT NULL,
  `prod_id` INT NOT NULL,
  PRIMARY KEY (`ima_id`),
  INDEX `fk_t_imagem_t_producto1_idx` (`prod_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_imagem_t_producto1`
    FOREIGN KEY (`prod_id`)
    REFERENCES `mydb`.`t_producto` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_categoria` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_nom` VARCHAR(95) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_categoriaproducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_categoriaproducto` (
  `catprod_id` INT NOT NULL AUTO_INCREMENT,
  `cat_id` INT NULL,
  `pro_id` INT NULL,
  PRIMARY KEY (`catprod_id`),
  INDEX `fk_t_categoriaproducto_t_categoria1_idx` (`cat_id` ASC) VISIBLE,
  INDEX `fk_t_categoriaproducto_t_producto1_idx` (`pro_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_categoriaproducto_t_categoria1`
    FOREIGN KEY (`cat_id`)
    REFERENCES `mydb`.`t_categoria` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_categoriaproducto_t_producto1`
    FOREIGN KEY (`pro_id`)
    REFERENCES `mydb`.`t_producto` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_destino` (
  `dest_id` INT NOT NULL,
  `dest_est` VARCHAR(20) NOT NULL,
  `dest_lat` DECIMAL(10,2) NOT NULL,
  `dest_lon` DECIMAL(10,2) NOT NULL,
  `compra_id` INT NOT NULL,
  PRIMARY KEY (`dest_id`),
  INDEX `fk_destino_compra1_idx` (`compra_id` ASC) VISIBLE,
  CONSTRAINT `fk_destino_compra1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `mydb`.`t_compra` (`compra_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
