-- MySQL Script generated by MySQL Workbench
-- Tue Oct 15 20:56:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_persona` (
  `per_id` INT NOT NULL,
  `per_nom` VARCHAR(45) NOT NULL,
  `per_ape` VARCHAR(45) NOT NULL,
  `per_dir` TEXT NOT NULL,
  `per_tel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`per_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_usuario` (
  `tusu_id` INT NOT NULL,
  `tusu_desc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tusu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_usuario` (
  `usu_id` INT NOT NULL,
  `usu_email` VARCHAR(45) NOT NULL,
  `usu_hash` TEXT NOT NULL,
  `usu_salt` TEXT NOT NULL,
  `usu_fechreg` DATE NOT NULL,
  `usu_fechses` DATE NOT NULL,
  `usu_imgurl` TEXT NULL,
  `per_id` INT NULL,
  `tusu_id` INT NULL,
  PRIMARY KEY (`usu_id`),
  INDEX `fk_t_usuario_t_persona1_idx` (`per_id` ASC) VISIBLE,
  INDEX `fk_t_usuario_Tipo_usuario1_idx` (`tusu_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_usuario_t_persona1`
    FOREIGN KEY (`per_id`)
    REFERENCES `mydb`.`t_persona` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_usuario_Tipo_usuario1`
    FOREIGN KEY (`tusu_id`)
    REFERENCES `mydb`.`Tipo_usuario` (`tusu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_color` (
  `color_id` INT NOT NULL AUTO_INCREMENT,
  `color_nom` VARCHAR(45) NULL,
  PRIMARY KEY (`color_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_marca` (
  `marca_id` INT NOT NULL AUTO_INCREMENT,
  `marca_nom` VARCHAR(45) NULL,
  PRIMARY KEY (`marca_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_modelo` (
  `mod_id` INT NOT NULL AUTO_INCREMENT,
  `mod_nom` VARCHAR(45) NULL,
  `marca_id` INT NULL,
  PRIMARY KEY (`mod_id`),
  INDEX `fk_t_modelo_t_marca1_idx` (`marca_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_modelo_t_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `mydb`.`t_marca` (`marca_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_tipovehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_tipovehiculo` (
  `tve_id` INT NOT NULL,
  `tve_nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tve_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_departamento` (
  `dpto_id` INT NOT NULL,
  `dpto_nom` VARCHAR(45) NULL,
  PRIMARY KEY (`dpto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_provincia` (
  `prov_id` INT NOT NULL,
  `prov_nom` VARCHAR(45) NULL,
  `dpto_id` INT NULL,
  PRIMARY KEY (`prov_id`),
  INDEX `fk_t_provincia_t_departamento1_idx` (`dpto_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_provincia_t_departamento1`
    FOREIGN KEY (`dpto_id`)
    REFERENCES `mydb`.`t_departamento` (`dpto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_distrito` (
  `dist_id` INT NOT NULL AUTO_INCREMENT,
  `dist_nom` VARCHAR(45) NULL,
  `prov_id` INT NULL,
  PRIMARY KEY (`dist_id`),
  INDEX `fk_t_distrito_t_provincia1_idx` (`prov_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_distrito_t_provincia1`
    FOREIGN KEY (`prov_id`)
    REFERENCES `mydb`.`t_provincia` (`prov_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_vehiculo` (
  `ve_id` INT NOT NULL,
  `ve_nrop` INT NOT NULL,
  `ve_nroa` INT NOT NULL,
  `ve_anio` INT NOT NULL,
  `ve_fechrt` DATE NOT NULL,
  `ve_prec` DECIMAL(10,2) NOT NULL,
  `ve_fechvs` DATE NOT NULL,
  `ve_poliza` VARCHAR(45) NOT NULL,
  `ve_placa` VARCHAR(45) NULL,
  `color_id` INT NULL,
  `mod_id` INT NULL,
  `tve_id` INT NULL,
  `dist_id` INT NULL,
  PRIMARY KEY (`ve_id`),
  INDEX `fk_t_vehiculo_t_color1_idx` (`color_id` ASC) VISIBLE,
  INDEX `fk_t_vehiculo_t_modelo1_idx` (`mod_id` ASC) VISIBLE,
  INDEX `fk_t_vehiculo_t_tipovehiculo1_idx` (`tve_id` ASC) VISIBLE,
  INDEX `fk_t_vehiculo_t_distrito1_idx` (`dist_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_vehiculo_t_color1`
    FOREIGN KEY (`color_id`)
    REFERENCES `mydb`.`t_color` (`color_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_vehiculo_t_modelo1`
    FOREIGN KEY (`mod_id`)
    REFERENCES `mydb`.`t_modelo` (`mod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_vehiculo_t_tipovehiculo1`
    FOREIGN KEY (`tve_id`)
    REFERENCES `mydb`.`t_tipovehiculo` (`tve_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_vehiculo_t_distrito1`
    FOREIGN KEY (`dist_id`)
    REFERENCES `mydb`.`t_distrito` (`dist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_alquiler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_alquiler` (
  `alqui_id` INT NOT NULL AUTO_INCREMENT,
  `alqui_fech` DATE NOT NULL,
  `alqui_fechin` DATE NOT NULL,
  `alqui_fechfin` DATE NOT NULL,
  `alqui_cost` DECIMAL(10,2) NOT NULL,
  `alqui_est` VARCHAR(45) NOT NULL,
  `usu_id` INT NULL,
  `ve_id` INT NULL,
  PRIMARY KEY (`alqui_id`),
  INDEX `fk_Alquiler_Usuario1_idx` (`usu_id` ASC) VISIBLE,
  INDEX `fk_t_alquiler_t_vehiculo1_idx` (`ve_id` ASC) VISIBLE,
  CONSTRAINT `fk_Alquiler_Usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `mydb`.`t_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_alquiler_t_vehiculo1`
    FOREIGN KEY (`ve_id`)
    REFERENCES `mydb`.`t_vehiculo` (`ve_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_imagenvehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_imagenvehiculo` (
  `ima_id` INT NOT NULL AUTO_INCREMENT,
  `ima_url` TEXT NULL,
  `ve_id` INT NULL,
  PRIMARY KEY (`ima_id`),
  INDEX `fk_t_imagenvehiculo_t_vehiculo1_idx` (`ve_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_imagenvehiculo_t_vehiculo1`
    FOREIGN KEY (`ve_id`)
    REFERENCES `mydb`.`t_vehiculo` (`ve_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_valoracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_valoracion` (
  `valo_id` INT NOT NULL,
  `valo_coment` TEXT NULL,
  `valo_punt` INT NULL,
  `alqui_id` INT NULL,
  PRIMARY KEY (`valo_id`),
  INDEX `fk_t_valoracion_t_alquiler1_idx` (`alqui_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_valoracion_t_alquiler1`
    FOREIGN KEY (`alqui_id`)
    REFERENCES `mydb`.`t_alquiler` (`alqui_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_dueniovehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_dueniovehiculo` (
  `dve_id` INT NOT NULL AUTO_INCREMENT,
  `usu_id` INT NULL,
  `ve_id` INT NULL,
  PRIMARY KEY (`dve_id`),
  INDEX `fk_t_dueniovehiculo_t_vehiculo1_idx` (`ve_id` ASC) VISIBLE,
  INDEX `fk_t_dueniovehiculo_t_usuario1_idx` (`usu_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_dueniovehiculo_t_vehiculo1`
    FOREIGN KEY (`ve_id`)
    REFERENCES `mydb`.`t_vehiculo` (`ve_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_dueniovehiculo_t_usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `mydb`.`t_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
